apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-devops-linux
  namespace: az-devops
  labels:
    app: az-devops-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-devops-linux
  template:
    metadata:
      labels:
        app: az-devops-linux
    spec:
      containers:
      - name: az-agent
        image: local/az-local-agent:v1.4.0
        imagePullPolicy: Never
        env:
          - name: DOTNET_EnableWriteXorExecute
            value: "0"
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock