trigger: none

pool: Local-kubernetes

stages:
- stage: Deploy
  jobs:
  - deployment: helloWorld
    displayName: 'Agent Setup'
    environment: 
      name: 'local-kubernetes-dev'
    strategy:
        runOnce:
          deploy:
            steps:
              - script: echo This runs in the default shell on any machine
              - bash: |
                  echo This multiline script always runs in Bash.
                  echo Even on Windows machines!